### ISSUE TITLE
classes don't work out of the box

### ISSUE THREAD

**Issue by happycollision** [babichjacob/svelte-add-tailwindcss#2]
Not sure what else to do to make classes work, but right now only styling with `@apply` directly in the component (the out-of-the-box changes make by your script) actually works. I defined a second version of the Counter component to compare and here is what I've got.

|code for second button|result|
|---|---|
|<img width="403" alt="CleanShot 2020-11-23 at 20 29 59@2x" src="https://user-images.githubusercontent.com/3663628/100034820-01fe8300-2dcb-11eb-85e2-d8c8e688ff8b.png">|<img width="460" alt="CleanShot 2020-11-23 at 20 28 21@2x" src="https://user-images.githubusercontent.com/3663628/100034824-0460dd00-2dcb-11eb-949a-87f29558415c.png">|

**Comment by happycollision** [comment]
All the latest code as of last night at around midnight Eastern time.

**Comment by babichjacob** [comment]
👋 Hi, sorry that you're encountering problems.

Is there still a `$layout.svelte` file with `import "./_global.pcss";` in it? That's what powers the utility classes.

**Comment by happycollision** [comment]
Yeah.
<img width="448" alt="CleanShot 2020-11-23 at 20 37 32@2x" src="https://user-images.githubusercontent.com/3663628/100035246-ba2c2b80-2dcb-11eb-91f6-17b497822476.png">

I am going to try and run a static site build here in a minute to see if it works there. Pictured in the issue is during dev. Doubt it'd make a difference, but worth ruling out I guess.

**Comment by happycollision** [comment]
And, hey! No problem. Just thought I'd let you know. (and I did force snowpack version as mentioned in an issue over at the postcss script repo

**Comment by babichjacob** [comment]
This is the content of `_global.pcss` right?

```css
@tailwind base;
@tailwind components;
@tailwind utilities;
```

**Comment by babichjacob** [comment]
I just did these exact steps to get the expected working result:

```sh
mkdir try-repro
cd try-repro
pnpm init svelte@next  # say yes to TypeScript
pnpx use-preset babichjacob/svelte-add-postcss --no-ssh  # say no to installing dependencies
pnpx use-preset babichjacob/svelte-add-tailwindcss --no-ssh  # say no to installing dependencies
pnpm install
pnpm run dev -- --open  # wait like 10 seconds for the CSS to compile and utility classes to work (outside of `@apply`)
```

**Comment by happycollision** [comment]
I'll try again with a brand new project...

**Comment by happycollision** [comment]
Hmmm. Works in the new repo. Same steps as last night, however the need to pin snowpack vanished, so maybe this was never an issue with this repo. Sorry to bother.

**Comment by babichjacob** [comment]
> Hmmm. Works in the new repo. Same steps as last night, however the need to pin snowpack vanished, so maybe this was never an issue with this repo. Sorry to bother.

It's not a problem! I like that there's interest in my projects and I can point to troubleshooting steps like this so that it's easier to help in the future.

**Comment by happycollision** [comment]
Wow. Ok. For those on macOS that find this issue: if your project is inside the old `~/Sites` directory, it is very possible that macOS is interfering somehow. So I wasn't crazy, but my machine was!

**Comment by pebezo** [comment]
@happycollision Same thing happened to me (Windows/WSL). @babichjacob recommended to start fresh and that worked. Something fishy going on somewhere :)

**Comment by babichjacob** [comment]
> @happycollision Same thing happened to me (Windows/WSL). @babichjacob recommended to start fresh and that worked. Something fishy going on somewhere :)

The preset might be overly sensitive to something or something. If this ever happens, create a repo and it'll be possible for me to identify what change the preset was supposed to apply but didn't.
